# note: use same title as in readme - otherwise gets duplicated on page
##    see the pages-themes/primer  for details

title: Blockchain Austria • Blockkette Österreich (Decentralized Hacker Edition)
